---

- import_tasks: sub_tasks/preq.yml
  tags: ['web_stack_deployment','web_stack_deployment.preq']

- import_tasks: sub_tasks/symlink.yml
  tags: ['web_stack_deployment','web_stack_deployment.symlink'] 

- import_tasks: sub_tasks/letsencrypt.yml
  tags: ['web_stack_deployment','web_stack_deployment.letsencrypt']

- import_tasks: sub_tasks/git.yml
  tags: ['web_stack_deployment','web_stack_deployment.git']

###############
#  CONFIG
###############

- name: Dump Config
  copy:
    content: "{{ vhost | to_nice_yaml(indent=2) }}"
    dest: "{{ httpd_dir_vhosts }}/{{ vhost.domainname }}/config/ansible.yml"

...
