---
# asible.web_stack/tasks/main.yml
- import_tasks: include-vars.yml
  tags: ['web_stack_deployment']

# Deploy Websites
- name: Deploy websites
  include_tasks: deploy.yml
  with_items: "{{ web_stack_deployment_websites }}"
  loop_control:
    loop_var: vhost
  notify: httpd restarted
...
