---

###############
# GIT Repo
###############

- name: Remove Document Root
  file:
    state: absent
    path: "{{ httpd_dir_vhosts }}/{{ vhost.domainname }}/www"
  when: "vhost.use_git == true"


- name: Deploy Git Repo
  git:
    repo: "{{ vhost.git_repo }}"
    dest: "{{ httpd_dir_vhosts }}/{{ vhost.domainname }}/www"
    clone: yes
    update: yes
    key_file: "{{ webstack_deployment_gitkey }}"
    accept_hostkey: yes
  when: "vhost.use_git == true"

- name: Change owner of Document Root
  file:
    state: directory
    path: "{{ httpd_dir_vhosts }}/{{ vhost.domainname }}/www"
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"
    recurse: yes
  when: "vhost.use_git == true"

- name: Check if ansible_deploy exists 
  stat:
    path: "{{ httpd_dir_vhosts }}/{{ vhost.domainname }}/www/ansible_deploy.sh" 
  register: ansible_deploy_stat

- name: Run ansible_deploy 
  command: "{{ httpd_dir_vhosts }}/{{ vhost.domainname }}/www/ansible_deploy.sh"
  args:
    chdir: "{{ httpd_dir_vhosts }}/{{ vhost.domainname }}/www/"
  ignore_errors: yes
  when: ansible_deploy_stat.stat.exists == True


- name: Apply SELinux context
  command: restorecon -irv {{ httpd_dir_vhosts }}/{{ vhost.domainname }}
  when: "deployment_use_selinux == 'yes'"


...
